### PR TITLE
[wip] PHP 8.1 compatibility

### PR DESCRIPTION
**Pull request by red-led**

### CODE REVIEW

**Comment by red-led** [comment]
@oohnoitz, to be honest I have no idea how to fix Travis CI builds.

[This](https://travis-ci.community/t/the-command-phpenv-global-8-1-failed-and-exited-with-1/12533) article suggests to add `dist: bionic`, but in this case `tests/install.sh` fails, cause there's no build for bionic.

Any ideas?

**Comment by oohnoitz** [comment]
We would need to get the install script updated. The simplest approach would be to switch all builds to `dist: bionic` and build sphinx and manticore from source instead of using the package manager.

**Comment by NelinD** [comment]
Is there any progress?

**Comment by red-led** [comment]
Nope =(

**Comment by oohnoitz** [comment]
I have some time to look into this right now. I'll get this merge in as-is.

**Pull request merged**
