### PR TITLE
Add setSelect() and getSelect() to modify select fields

### LINKED ISSUE #51: select()
I have another question.
Here is an example:
```php
$firstQuery = (new SphinxQL($connection))->select(['id', 'name'])
->from('index_user');

$secondQuery = clone $firstQuery;
$count = $secondQuery->select(SphinxQL::expr('COUNT(*)'))->execute();
$items = $firstQuery->execute();
```
But this code will not work, because we have this line in select method:
```php
$this->reset();
```
It is not very nice. Do you think it's necessary?
It would be great to be able to change select clause.

### PR DESCRIPTION
**Pull request by alpha0010**
Fixes #51

### CODE REVIEW

**Comment by alpha0010** [comment]
Hmm... it looks like we found a bug in Sphinx. I will investigate.

**Comment by alpha0010** [comment]
Reported: http://sphinxsearch.com/bugs/view.php?id=2519

**Comment by oohnoitz** [comment]
once its fixed in sphinx, i'll get this merged in.

**Comment by alpha0010** [comment]
It appears the problem is our [`HAVING`](https://github.com/FoolCode/SphinxQL-Query-Builder/blob/master/tests/SphinxQL/SphinxQLTest.php#L651-L655) test (which is unrelated to this pull). Technically that specific query can be rewritten as:
```php
$result = SphinxQL::create(self::$conn)->select(SphinxQL::expr('count(*) as cnt'))
    ->from('rt')
    ->where('gid', 304)
    ->groupBy('gid')
    ->execute();
```
Maybe the Sphinx team decided `HAVING` should only be used in cases that `WHERE` is not applicable (for example, `COUNT(*) > 123`).  I suppose we will have to wait for their developers to say if this is intended behaviour.

**Comment by oohnoitz** [comment]
it does seem like it's a regression since the test hadn't failed on the `beta` release on previous build versions.

although rewriting the query to the one you've provided would cause the test to pass, it would defeat the purpose of having the test in the first place, since we are checking to make sure that the `HAVING` query built is working and valid. but as you've stated, we'll just need to wait hear from the team themselves.

**Comment by oohnoitz** [comment]
`HAVING` tests will be updated in the #107 PR once tests pass.

**Pull request merged**
