### PR TITLE
Improve test coverage

### PR DESCRIPTION
**Pull request by alpha0010**
classes 33% -> 54%, methods 62% -> 81%, lines 75% -> 93%

Fixed a few small bugs in the process.

### CODE REVIEW

**Comment by alpha0010** [comment]
Any ideas why hhvm failed to throw an exception?

**Comment by woxxy** [comment]
I can reproduce this locally. 

I will try to write a minimal script to reproduce this difference between HHVM and PHP. It's very likely it's an HHVM quirk.

**Comment by woxxy** [comment]
Testing script:
```php
<?php

$mysqli = new Mysqli('127.0.0.1', null, null, null, 9306, null);

if (!$mysqli->multi_query('weiuhfuiwehfiuw')) {
    echo "Multi query failed: (" . $mysqli->errno . ") " . $mysqli->error;
}
```

Testing PHP vs HHVM.
```bash
$ php testing.php
Multi query failed: (1064) sphinxql: syntax error, unexpected IDENT, expecting ALTER (or 20 other tokens) near 'weiuhfuiwehfiuw' 
$ hhvm testing.php
Multi query failed: (0) %
```

We have an HHVM quirk: it does notice there's an error, but it doesn't set the error number or string. I need to test this against a MySQL server as well, but surely this is an HHVM bug. Then I will proceed filing a bug in HHVM's issue tracker.

I fixed this library's code in `master` so it works.

**Comment by woxxy** [comment]
I've filed the issue on HHVM's Github issues: https://github.com/facebook/hhvm/issues/5602

**Comment by woxxy** [comment]
Checked the changes, looks fine to me. Thanks for cleaning up the code itself as well! 

```php
-            if ($character === '\\') {
-                $result[$character] = '\\\\';
-            } else {
-                $result[$character] = '\\'.$character;
-            }
+            $result[$character] = '\\'.$character;
```

more-wine

**Pull request merged**
