### PR TITLE
Fix crash on foreach with empty ResultSet

### PR DESCRIPTION
**Pull request by alpha0010**
Cannot rewind to row 0 if no rows were retrieved.

### CODE REVIEW

**Comment by alpha0010** [comment]
Oh dear... I think I need to test my test cases better.

**Comment by alpha0010** [comment]
Travis error running composer?

**Comment by oohnoitz** [comment]
@alpha0010 yeah, it happens randomly. It would be great if we can use the new build containers and cache the `vendor/` directory, but we won't be able to install sphinxsearch.

**Comment by alpha0010** [comment]
@oohnoitz I will browse the documentation on using build containers.  Who knows, I might be able to hack something together.

**Comment by oohnoitz** [comment]
@alpha0010 Here is the documentation about `apt` packages and sources for the new container builds: http://docs.travis-ci.com/user/apt/

**Pull request merged**
