### PR TITLE
Getter/Setter for $where array

### PR DESCRIPTION
**Pull request by goodluck81**
Useful for cases when we need to reset specific where conditions for faceting. I'm using this in production and I think i'm not the only one :)
Thanks!

### CODE REVIEW

**Comment by oohnoitz** [comment]
@goodluck81 can you write some simple unit tests for these?

**Comment by oohnoitz** [comment]
I'm not exactly sure what this is suppose to achieve anymore. Is the goal to reset the compiled `where` syntax or replace it?

**Comment by goodluck81** [comment]
The goal is to remove custom where condition from builder in order to facet it.

My usage is something like this:

$reset_query->setWhere(array_values(array_filter($query->getWhere(), function($x) use ($facet){ return $x["column"]!==$facet; })))->limit(1,1)->facet(Facet::create($this->conn)->facet($facet)->orderByFunction('COUNT','*', 'DESC')->limit(999));

**Comment by goodluck81** [comment]
No, $reset_query is just new instance of "SphinxQL::create" that clone the where query of the main query (before get limit/order and executeBatch), removing the where condition only for $reset_query. Main query is not affected, for example we have 3 filters: job_department_id=1, job_contract_id=1 and job_city_id=222 (last one applied). I need to facet the job_city_id for department and contract so I need main query but without job_city_id, so I simply cone the main query before it get executed and unset the job_city_id where condition.

**Comment by woxxy** [comment]
@goodluck81 thanks for explaining. The correct solution is not different, you should split the query building between PHP functions and conditionally call them to build one or the other query.

Again, I won't implement functionality that allows entry to private variables.

**Pull request closed without merging**
