### PR TITLE
Add support of HAVING

### PR DESCRIPTION
**Pull request by xzander**

### CODE REVIEW

**Comment by xzander** [comment]
Add support of HAVING in SELECT queries:
        $result = SphinxQL::create($this->conn)->select(SphinxQL::expr('count(*) as cnt'))
            ->from('rt')
            ->groupBy('gid')
            ->having('cnt', '>', 1)
            ->execute();

**Comment by versh23** [comment]
can we change travis to latest release of sphinx ? 
http://sphinxsearch.googlecode.com/svn/branches/rel22/

currently is rel21

**Comment by xzander** [comment]
I think yes. I tested it on 2.2.4 version. All tests passed successfully.

**Comment by oohnoitz** [comment]
@xzander can you rebase your PR since I pushed the changes from the `resultset` branch into `master`.

**Comment by xzander** [comment]
I did something wrong, i will reopen new pull request with right changes

**Pull request closed without merging**
